import { Report } from "@/types/report";
import { User, ResidentProfile } from "@/types/user";
import { AppNotification } from "@/types/notification";
import { Announcement } from "@/types/announcement";

export const mockCurrentUser: ResidentProfile = {
  id: "RES-001",
  name: "Juan Dela Cruz",
  email: "juan.delacruz@email.com",
  role: "resident",
  phone: "+63 917 123 4567",
  address: "Block 4, Lot 12, Mahogany St., Riverside",
  barangay: "Barangay Poblacion, Butuan City",
  avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80",
  joinedDate: "January 15, 2024",
  totalReports: 12,
  resolvedReports: 9,
  pendingReports: 3,
};

export const mockAdminUser: User = {
  id: "ADM-001",
  name: "Hon. Maria Santos",
  email: "admin.santos@butuancity.gov.ph",
  role: "admin",
  phone: "+63 918 987 6543",
  address: "Barangay Hall Office, J.C. Aquino Ave.",
  barangay: "Barangay Poblacion, Butuan City",
  avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80",
  joinedDate: "October 1, 2022",
};

export const reports: Report[] = [
  {
    id: "BR-0003",
    residentId: "RES-001",
    residentName: "Juan Dela Cruz",
    category: "Illegal Dumping",
    subject: "Garbage along the river bank",
    description: "Improper waste disposal and accumulated plastic trash near the riverside park area causing foul odor and blocking water drainage.",
    location: "Riverside Park, Purok 3, Butuan City",
    dateSubmitted: "Apr 28, 2025",
    status: "in-progress",
    priority: "high",
    image: "https://images.unsplash.com/photo-1605600659908-0ef719419d41?auto=format&fit=crop&w=800&q=80",
    adminNotes: "Waste management team dispatched for scheduled clean-up on Thursday morning.",
    timeline: [
      {
        id: "TL-01",
        status: "submitted",
        title: "Report Submitted",
        description: "Report filed by resident via mobile web portal.",
        timestamp: "Apr 28, 2025, 08:30 AM",
        updatedBy: "Juan Dela Cruz",
      },
      {
        id: "TL-02",
        status: "under-review",
        title: "Under Barangay Review",
        description: "Verified by Desk Officer and forwarded to Environmental Sanitation.",
        timestamp: "Apr 28, 2025, 11:15 AM",
        updatedBy: "Officer B. Ramos",
      },
      {
        id: "TL-03",
        status: "in-progress",
        title: "Clean-up Scheduled & In Progress",
        description: "Sanitation truck and team deployed for site clearing operations.",
        timestamp: "Apr 29, 2025, 09:00 AM",
        updatedBy: "Sanitation Supervisor",
      },
    ],
  },
  {
    id: "BR-0004",
    residentId: "RES-001",
    residentName: "Juan Dela Cruz",
    category: "Street Light Out",
    subject: "Flickering and dead street lights",
    description: "Three consecutive street light fixtures are completely dark along Rosal Street, making it unsafe for pedestrians at night.",
    location: "Rosal St., Purok 5, Butuan City",
    dateSubmitted: "Apr 27, 2025",
    status: "resolved",
    priority: "medium",
    image: "https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80",
    adminNotes: "Electrician replaced 3 LED bulbs and repaired wiring junction box.",
    timeline: [
      {
        id: "TL-04",
        status: "submitted",
        title: "Report Submitted",
        description: "Resident filed ticket for dark street lights.",
        timestamp: "Apr 27, 2025, 07:45 PM",
        updatedBy: "Juan Dela Cruz",
      },
      {
        id: "TL-05",
        status: "in-progress",
        title: "Repair Team Dispatched",
        description: "City engineering maintenance crew on site.",
        timestamp: "Apr 28, 2025, 02:00 PM",
        updatedBy: "Eng. D. Cruz",
      },
      {
        id: "TL-06",
        status: "resolved",
        title: "Issue Fixed & Tested",
        description: "LED fixtures replaced and operational.",
        timestamp: "Apr 29, 2025, 05:30 PM",
        updatedBy: "Eng. D. Cruz",
      },
    ],
  },
  {
    id: "BR-0005",
    residentId: "RES-002",
    residentName: "Maria Clara Lopez",
    category: "Road Repair",
    subject: "Deep pothole creating traffic hazard",
    description: "Deep pothole in the middle lane after continuous heavy rainfall. Vehicles swerve abruptly to avoid damage.",
    location: "Corner Narra & Acacia Ave., Butuan City",
    dateSubmitted: "Apr 26, 2025",
    status: "under-review",
    priority: "high",
    image: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80",
    adminNotes: "Assessing if asphalt patching or full concrete overlay is required with DPWH.",
    timeline: [
      {
        id: "TL-07",
        status: "submitted",
        title: "Report Submitted",
        description: "Filed with photographic evidence.",
        timestamp: "Apr 26, 2025, 10:20 AM",
        updatedBy: "Maria Clara Lopez",
      },
      {
        id: "TL-08",
        status: "under-review",
        title: "Site Inspection Scheduled",
        description: "Road inspector assigned to measure dimensions.",
        timestamp: "Apr 27, 2025, 09:30 AM",
        updatedBy: "Admin Maria Santos",
      },
    ],
  },
  {
    id: "BR-0006",
    residentId: "RES-003",
    residentName: "Antonio Luna",
    category: "Flooding",
    subject: "Blocked culvert causing knee-deep flood",
    description: "Culvert drainage clogged with silt and debris causing water to overflow into adjacent residential yards during rain.",
    location: "Lower Purok 2, near Barangay Chapel",
    dateSubmitted: "Apr 25, 2025",
    status: "submitted",
    priority: "urgent",
    image: "https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=800&q=80",
    adminNotes: "Awaiting review queue assignment.",
    timeline: [
      {
        id: "TL-09",
        status: "submitted",
        title: "Report Submitted",
        description: "Urgent ticket received by system.",
        timestamp: "Apr 25, 2025, 04:15 PM",
        updatedBy: "Antonio Luna",
      },
    ],
  },
  {
    id: "BR-0007",
    residentId: "RES-001",
    residentName: "Juan Dela Cruz",
    category: "Animal Control",
    subject: "Stray aggressive dogs wandering near school",
    description: "Pack of 4 stray dogs chasing students and motorcycles near the Elementary School gate during dismissal.",
    location: "Poblacion Central Elementary School zone",
    dateSubmitted: "Apr 24, 2025",
    status: "rejected",
    priority: "medium",
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=800&q=80",
    adminNotes: "Referred to City Veterinary Services as jurisdiction falls outside local barangay pound ordinance.",
    timeline: [
      {
        id: "TL-10",
        status: "submitted",
        title: "Report Submitted",
        description: "Ticket logged by resident.",
        timestamp: "Apr 24, 2025, 01:10 PM",
        updatedBy: "Juan Dela Cruz",
      },
      {
        id: "TL-11",
        status: "rejected",
        title: "Referred to City Vet",
        description: "Direct endorsement made to Butuan City Veterinary Office Hotlines.",
        timestamp: "Apr 25, 2025, 10:00 AM",
        updatedBy: "Hon. Maria Santos",
      },
    ],
  },
  {
    id: "BR-0008",
    residentId: "RES-004",
    residentName: "Elena Silang",
    category: "Water Supply Issue",
    subject: "Low water pressure and brown tap water",
    description: "Water pressure has dropped significantly since yesterday and water running from faucets has noticeable brown sedimentation.",
    location: "Bougainvillea St., Purok 4",
    dateSubmitted: "Apr 23, 2025",
    status: "resolved",
    priority: "high",
    image: "https://images.unsplash.com/photo-1584727638096-042c45049ebe?auto=format&fit=crop&w=800&q=80",
    adminNotes: "Butuan City Water District completed main pipe flushing.",
    timeline: [
      {
        id: "TL-12",
        status: "submitted",
        title: "Report Submitted",
        description: "Water quality issue recorded.",
        timestamp: "Apr 23, 2025, 06:40 AM",
        updatedBy: "Elena Silang",
      },
      {
        id: "TL-13",
        status: "resolved",
        title: "Water Line Cleared",
        description: "BCWD coordinated flushing complete; clarity restored.",
        timestamp: "Apr 24, 2025, 03:00 PM",
        updatedBy: "BCWD Liaison",
      },
    ],
  },
];

export const mockResidents: ResidentProfile[] = [
  mockCurrentUser,
  {
    id: "RES-002",
    name: "Maria Clara Lopez",
    email: "maria.lopez@example.com",
    role: "resident",
    phone: "+63 919 234 5678",
    address: "Purok 1, Riverside, Butuan City",
    barangay: "Barangay Poblacion, Butuan City",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
    joinedDate: "February 10, 2024",
    totalReports: 6,
    resolvedReports: 4,
    pendingReports: 2,
  },
  {
    id: "RES-003",
    name: "Antonio Luna",
    email: "antonio.luna@example.com",
    role: "resident",
    phone: "+63 920 345 6789",
    address: "Lower Purok 2, Butuan City",
    barangay: "Barangay Poblacion, Butuan City",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    joinedDate: "March 5, 2024",
    totalReports: 4,
    resolvedReports: 3,
    pendingReports: 1,
  },
  {
    id: "RES-004",
    name: "Elena Silang",
    email: "elena.silang@example.com",
    role: "resident",
    phone: "+63 921 456 7890",
    address: "Bougainvillea St., Purok 4, Butuan City",
    barangay: "Barangay Poblacion, Butuan City",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
    joinedDate: "March 20, 2024",
    totalReports: 8,
    resolvedReports: 7,
    pendingReports: 1,
  },
  {
    id: "RES-005",
    name: "Jose Rizal Mercado",
    email: "jose.rizal@example.com",
    role: "resident",
    phone: "+63 922 567 8901",
    address: "Ilustrado Ave., Purok 6, Butuan City",
    barangay: "Barangay Poblacion, Butuan City",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    joinedDate: "April 2, 2024",
    totalReports: 3,
    resolvedReports: 3,
    pendingReports: 0,
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: "ANN-001",
    title: "Community Clean-Up Drive & Dengue Prevention",
    content: "Join us this Saturday, May 3, 2025 at 6:00 AM for the Barangay-wide Oplan Clean-up. Volunteers will assemble at the Barangay Covered Court. Refreshments and certificates provided.",
    category: "Community Event",
    author: "Hon. Maria Santos",
    authorRole: "Barangay Captain",
    datePosted: "Apr 28, 2025",
    priority: "high",
    isActive: true,
    targetAudience: "all",
  },
  {
    id: "ANN-002",
    title: "Scheduled Power Interruption Notice",
    content: "ANECO advisory: Scheduled power service maintenance will affect Purok 2, 3, and 5 on Sunday, May 4, 2025 from 8:00 AM to 4:00 PM for transformer upgrading.",
    category: "Public Advisory",
    author: "Barangay Secretariat",
    authorRole: "Administrative Staff",
    datePosted: "Apr 27, 2025",
    priority: "urgent",
    isActive: true,
    targetAudience: "residents",
  },
  {
    id: "ANN-003",
    title: "Free Anti-Rabies Vaccination for Pets",
    content: "In partnership with City Vet, free anti-rabies vaccination and pet deworming clinic will be held at the Multi-Purpose Hall on May 10, 2025 from 9:00 AM to 3:00 PM.",
    category: "Health & Services",
    author: "Health Committee",
    authorRole: "Barangay Kagawad",
    datePosted: "Apr 26, 2025",
    priority: "medium",
    isActive: true,
    targetAudience: "residents",
  },
  {
    id: "ANN-004",
    title: "Barangay Assembly & 1st Quarter Financial Report",
    content: "All registered resident voters are invited to attend the General Barangay Assembly on May 17, 2025 at 1:00 PM at the Barangay Gymnasium.",
    category: "Governance",
    author: "Hon. Maria Santos",
    authorRole: "Barangay Captain",
    datePosted: "Apr 20, 2025",
    priority: "low",
    isActive: false,
    targetAudience: "all",
  },
];

export const mockNotifications: AppNotification[] = [
  {
    id: "NOTIF-001",
    userId: "RES-001",
    title: "Report Status Updated",
    message: "Your report BR-0003 (Garbage along the river bank) is now In Progress. Sanitation crew has been assigned.",
    type: "status_update",
    date: "10 minutes ago",
    read: false,
    reportId: "BR-0003",
    linkUrl: "/resident/reports/BR-0003",
  },
  {
    id: "NOTIF-002",
    userId: "RES-001",
    title: "Street Light Report Resolved",
    message: "Your report BR-0004 (Street Light Out on Rosal St.) has been marked as Resolved. Thank you for your alert!",
    type: "status_update",
    date: "1 day ago",
    read: true,
    reportId: "BR-0004",
    linkUrl: "/resident/reports/BR-0004",
  },
  {
    id: "NOTIF-003",
    userId: "RES-001",
    title: "New Barangay Announcement",
    message: "Community Clean-Up Drive & Dengue Prevention is scheduled for this coming Saturday.",
    type: "announcement",
    date: "2 days ago",
    read: false,
    linkUrl: "/resident/dashboard",
  },
  {
    id: "NOTIF-004",
    userId: "RES-001",
    title: "Profile Information Verified",
    message: "Your resident proof of residency was successfully verified by the Barangay desk.",
    type: "system",
    date: "5 days ago",
    read: true,
    linkUrl: "/resident/profile",
  },
];
